### PR TITLE
Support for 2D steering

### PR DESCRIPTION
**Pull request by prasadtiru**
Added the following features:

1.  Support for 2D steering.

### CODE REVIEW

**Comment by mchitre** [comment]
In the spirit of avoiding duplicate functionality across the Julia ecosystem, would one of these not suffice?
- [VectorizedRoutines.jl](https://github.com/ChrisRackauckas/VectorizedRoutines.jl)
- [Iterators.product](https://stackoverflow.com/questions/44581049/utilizing-ndgrid-meshgrid-functionality-in-julia)

...for the functionality in 2 and 3.

**Comment by baggepinnen** [comment]
`LinRange2D` can be recreated using broadcast like so
```julia
julia> reduce(vcat, hcat.(LinRange(0,1,4)', LinRange(2,3,5)))
20×2 Array{Float64,2}:
 0.0       2.0
 0.0       2.25
 0.0       2.5
 0.0       2.75
 0.0       3.0
 0.333333  2.0
 0.333333  2.25
 0.333333  2.5
 0.333333  2.75
 0.333333  3.0
 0.666667  2.0
 0.666667  2.25
 0.666667  2.5
 0.666667  2.75
 0.666667  3.0
 1.0       2.0
 1.0       2.25
 1.0       2.5
 1.0       2.75
 1.0       3.0
```

**Comment by prasadanjangi** [comment]
prof @mchitre : I've now removed both `LinRange2D` and `meshgrid` from this file since these were just convenient functions. These can be implemented by anyone utilizing existing libraries as you pointed out. I've also updated the documentation accordingly. 

@baggepinnen Thanks. That works!

**Comment by mchitre** [comment]
@prasadtiru could you add some test cases for this please? Also, would be good to note in the doc that θ can be 1D or 2D angles, and not replace with 1D by 2D.

**Comment by prasadanjangi** [comment]
I've now added tests for testing the 2D steering code and fixed the documentation as suggested.

**Comment by baggepinnen** [comment]
The code contains a lot of `if` statements to handle the cases vector vs. matrix. It would perhaps be cleaner and more idiomatic julia to have two separate methods
```julia
steering(rxpos, c, θ::AbstractVector)
steering(rxpos, c, θ::AbstractMatrix)
```
and get rid of all `if` statements.

Note also that
```julia
ndims(θ) == 1 ? ndir = length(θ) : ndir = size(θ, 1)
```
is the same as 
```julia
ndir = size(θ, 1)
```

**Comment by prasadanjangi** [comment]
I've added a separate method now as suggested to deal with cases `vector` vs `matrix`.

**Review by mchitre — APPROVED** [review]

**Pull request merged**
